# name                    cpu     memo
# ------------------------------------
# nginx                   0,1     20
# postgres-backend        0,4     100
# redis                   0,2     30
# payment-proxy-one       0,1     40
# payment-proxy-two       0,1     40
# payment-worker          0,5     100
# payment-life-checker    0,1     20

services:
  postgres-backend:
    image: postgres:17-alpine
    container_name: postgres-backend
    hostname: postgres-backend
    networks:
      - backend
    environment:
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha
      POSTGRES_DB: rinha
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100MB"
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    networks:
      - backend
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"
    restart: unless-stopped

  payment-proxy-one:
    build:
      context: ./payment-proxy
    hostname: payment-proxy-one
    networks:
      - backend
    environment:
      - WATCH_FILES=0
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"
    depends_on:
      - postgres-backend
      - redis
    restart: unless-stopped

  payment-proxy-two:
    build:
      context: ./payment-proxy
    hostname: payment-proxy-two
    networks:
      - backend
    environment:
      - WATCH_FILES=0
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"
    depends_on:
      - postgres-backend
      - redis
    restart: unless-stopped

  payment-worker:
    build:
      context: ./payment-worker
    hostname: payment-worker
    networks:
      - backend
      - payment-processor
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - WATCH_FILES=0
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100MB"
    depends_on:
      - postgres-backend
      - redis

  payment-life-checker:
    build:
      context: ./payment-life-checker
    hostname: payment-life-checker
    networks:
      - backend
      - payment-processor
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - WATCH_FILES=0
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "40MB" # alterar isso aqui
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "50MB" # alterar isso aqui
    depends_on:
      - payment-proxy-one
      - payment-proxy-two

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

volumes:
  postgres_data:
    driver: local
