### payment-proxy endpoints ###
# @paymentProxyUrl = http://localhost:3001
@paymentProxyUrl = http://localhost:9999

### Healthcheck
GET {{paymentProxyUrl}}/healthcheck

### Fazer pagamento
POST {{paymentProxyUrl}}/payments
Content-Type: application/json

{
  "correlationId": "{{$guid}}",
  "amount": 1.0
}

### Resumo de pagamentos
GET {{paymentProxyUrl}}/payments-summary?from=2025-07-01T00:00:00.000Z&to=2025-07-30T00:00:00.000Z

### Limpa o banco
DELETE {{paymentProxyUrl}}/payments


### payment-processor-default endpoints ###############################################################################
@processorDefaultUrl = http://localhost:8001

### Fazer um pagamento
POST {{processorDefaultUrl}}/payments
Content-Type: application/json

{
  "correlationId": "{{$guid}}",
  "amount": 19.90,
  "requestedAt": "2025-07-11T20:53:00.000Z"
}

### Service health
GET {{processorDefaultUrl}}/payments/service-health

### Resumo dos pagamentos
GET {{processorDefaultUrl}}/admin/payments-summary?from=2025-07-01T20:50:00.000Z&to=2025-07-30T20:55:00.000Z
X-Rinha-Token: 123

### Detalhar pagamento
GET {{processorDefaultUrl}}/payments/c3123a89-5f73-44ec-9ed0-6806161ffb9f
X-Rinha-Token: 123

### Limpar banco de dados
POST {{processorDefaultUrl}}/admin/purge-payments
X-Rinha-Token: 123

### Configura falha
PUT {{processorDefaultUrl}}/admin/configurations/failure
Content-Type: application/json
X-Rinha-Token: 123

{
  "failure": false
}

### Configura delay
PUT {{processorDefaultUrl}}/admin/configurations/delay
Content-Type: application/json
X-Rinha-Token: 123

{
    "delay" : 0
}


### payment-processor-fallback endpoints ##################################################################################
@processorFallbackUrl = http://localhost:8002

### Service health
GET {{processorFallbackUrl}}/payments/service-health

### Resumo dos pagamentos
GET {{processorFallbackUrl}}/admin/payments-summary?from=2025-07-01T20:50:00.000Z&to=2025-07-30T20:55:00.000Z
X-Rinha-Token: 123

### Limpar banco de dados
POST {{processorFallbackUrl}}/admin/purge-payments
X-Rinha-Token: 123

### Configura falha
PUT {{processorFallbackUrl}}/admin/configurations/failure
Content-Type: application/json
X-Rinha-Token: 123

{
  "failure": false
}

### Configura delay
PUT {{processorFallbackUrl}}/admin/configurations/delay
Content-Type: application/json
X-Rinha-Token: 123

{
    "delay" : 0
}