services:
  payment-proxy-one:
    build: .
    hostname: payment-proxy-one
    networks:
      - backend
    environment:
      - WATCH_FILES=${WATCH_FILES:-0}
    ports:
      - 3001:3000
    volumes:
      - ".:/app"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "150MB"

networks:
  backend:
    external: true
  payment-processor:
    external: true
