services:
  payment-life-checker:
    # image: <seu-usuario-dockerhub>/payment-life-checker:latest
    build: .
    hostname: payment-life-checker
    networks:
      - backend
      - payment-processor
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - WATCH_FILES=0
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "40MB"

networks:
  backend:
    external: true
  payment-processor:
    external: true
