services:
  payment-worker-one:
    build: .
    hostname: payment-worker-one
    networks:
      - backend
      - payment-processor
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - WATCH_FILES=${WATCH_FILES:-0}
    ports:
      - 3002:3000
    volumes:
      - ".:/app"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "150MB"

networks:
  backend:
    external: true
  payment-processor:
    external: true
