services:
  payment-worker-one:
    # image: <seu-usuario-dockerhub>/payment-worker:latest
    build: .
    hostname: payment-worker-one
    networks:
      - backend
      - payment-processor
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - WATCH_FILES=0
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "600MB"

networks:
  backend:
    external: true
  payment-processor:
    external: true
