services:
  db:
    image: postgres:17-alpine
    container_name: postgres-backend
    hostname: postgres-backend
    networks:
      - backend
    environment:
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha
      POSTGRES_DB: rinha
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "96MB"
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  backend:
    external: true
