services:
  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    networks:
      - backend
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "200MB"
    restart: unless-stopped

volumes:
  redis_data:

networks:
  backend:
    external: true
